schema_version: 1

context:
  name: sqlframe
  version: "3.39.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sqlframe-${{ version }}.tar.gz
  sha256: 38304d1402ffaf5eaaae2701749f69c58eb5e339769e4e6b932ecc734c211284

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools-scm
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - prettytable <4
    - sqlglot >=24.0.0
    - typing_extensions

tests:
  - python:
      imports:
        - sqlframe
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Turning PySpark Into a Universal DataFrame API
  license: MIT
  license_file:
    - LICENSE
  homepage: https://github.com/eakmanrq/sqlframe

extra:
  recipe-maintainers:
    - nicornk
    - eakmanrq
